### ISSUE TITLE
Instrumentation

### ISSUE THREAD

**Issue by ontoconsult** [ProteusXML/proteusxml#3]
I have a few issues regarding instrumentation in the Proteus 4.0.1 schema:
1. ProcessInstrument has been renamed in the RDL to InstrumentationItem
2. ProcessInstrumentationFunction has been renamed in the RDL to InstrumentationFunction; this is because not all instrumentation functions are process related, and it is impossible to draw a line between those who are and those who aren't.
3. It appears to me that the Proteus 4.0.1 schema has been tailored to IEC 62424 leaving users of ANSI/API5.1 in the dark. Mind you, there is also an ISO standard for instrumentation on P&IDs: ISO 14617-6. 
[318299309-ISO-14617-6-2002.pdf](https://github.com/ProteusXML/proteusxml/files/1368869/318299309-ISO-14617-6-2002.pdf)
 I expect that the Proteus schema is extended to cover that ISO standard as well.

**Comment by sommersohn** [comment]
Thanks for your comments. Are these 3 issues or just one?
If these are three issues, could you be so kind and split it up into three different issues? That would make it easier to discuss about these issues. Thank you so much.

**Comment by ontoconsult** [comment]
It is one issue regarding instrumentation.
